// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using StudentManagement.API.DataAccess;

namespace StudentManagement.API.Migrations
{
  [DbContext(typeof(StudentDbContext))]
  partial class StudentDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.1.32")
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("StudentManagement.Models.StudentNS.Student", b =>
          {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<string>("Branch")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Name")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Section")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Year")
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("students");
          });
#pragma warning restore 612, 618
    }
  }
}
